### ISSUE TITLE
I have some questions about datasets need your help

### ISSUE THREAD

**Issue by ghost** [gaurav104/WSS-CMER#1]
I found from the code that you converted the data to png format. I would like to ask you for a more detailed data description. BranTS data has many channels. How do you deal with each piece of data? Should we select only one fixed channel to form a set of pictures, or separate all the channels and each channel forms a set of pictures?

Can you provide a copy of the running steps of the code? I will thank you very much.

**Comment by gaurav104** [comment]
Hi!
I have simply converted the 3D volumes to 2D slices/images and saved them as png. Below I provide the folder structure to save the images
-| brats_data
----| train/
--------| GT/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T1/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T2/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T1c/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_Flair/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
----| val/
--------| GT/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T1/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T2/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T1c/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_Flair/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
----| test/
--------| GT/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T1/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T2/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_T1c/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png
--------| MR_Flair/
------------| XXX0_001.png
------------| XXX1_002.png
------------| ....
------------| <patient_id>_<slice_number>.png

If you still have any queries feel free to reply._

**Comment by ghost** [comment]
> Hi!
> I have simply converted the 3D volumes to 2D slices/images and saved them as png. Below I provide the folder structure to save the images
> -| brats_data
> ----| train/
> --------| GT/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png --------| MR_T1/ ------------| XXX0_001.png ------------| XXX1_002.png ------------| .... ------------| <patient_id>_<slice_number>.png
> --------| MR_T2/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png --------| MR_T1c/ ------------| XXX0_001.png ------------| XXX1_002.png ------------| .... ------------| <patient_id>_<slice_number>.png
> --------| MR_Flair/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png ----| val/ --------| GT/ ------------| XXX0_001.png ------------| XXX1_002.png ------------| .... ------------| <patient_id>_<slice_number>.png
> --------| MR_T1/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png --------| MR_T2/ ------------| XXX0_001.png ------------| XXX1_002.png ------------| .... ------------| <patient_id>_<slice_number>.png
> --------| MR_T1c/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png --------| MR_Flair/ ------------| XXX0_001.png ------------| XXX1_002.png ------------| .... ------------| <patient_id>_<slice_number>.png
> ----| test/
> --------| GT/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png --------| MR_T1/ ------------| XXX0_001.png ------------| XXX1_002.png ------------| .... ------------| <patient_id>_<slice_number>.png
> --------| MR_T2/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png --------| MR_T1c/ ------------| XXX0_001.png ------------| XXX1_002.png ------------| .... ------------| <patient_id>_<slice_number>.png
> --------| MR_Flair/
> ------------| XXX0_001.png
> ------------| XXX1_002.png
> ------------| ....
> ------------| <patient_id>_<slice_number>.png
> 
> If you still have any queries feel free to reply._

Thank you very much!
